services:
  - type: web
    name: sistem-uks-sekolah
    env: python
    runtime: python-3.11.9
    buildCommand: "pip install --upgrade pip && cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true